(function(){
  'use strict';
  var app=document.getElementById('app'),toastEl=document.getElementById('toast');
  var avatars=['🐰','🐻','🐱','🦊','🐼'];
  var state={nickname:'',avatar:'🐰',count:8,ids:[],answers:[],index:0,role:'host',channel:null,busy:false};
  var isGoogle=typeof google!=='undefined'&&google.script&&google.script.run;
  var configuredUrl=String(window.TONGPIN_CONFIG&&window.TONGPIN_CONFIG.appsScriptUrl||'').trim();
  var remoteUrl=/^https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]+\/exec$/.test(configuredUrl)?configuredUrl:'';
  function esc(s){return String(s==null?'':s).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c];});}
  function toast(message){toastEl.textContent=message;toastEl.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(function(){toastEl.classList.remove('show');},2200);}
  function requestId(){return (crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2));}
  function setBusy(value){state.busy=value;document.querySelectorAll('button,input').forEach(function(el){if(el.id!=='music')el.disabled=value;});}
  function localDb(){try{return JSON.parse(localStorage.getItem('tongpin-radio-db')||'{\"channels\":{}}');}catch(e){return {channels:{}};}}
  function saveLocal(db){localStorage.setItem('tongpin-radio-db',JSON.stringify(db));}
  function localRpc(req){
    var db=localDb(),p=req.payload||{},ch,now=Date.now();
    Object.keys(db.channels).forEach(function(id){if(db.channels[id].expiresAt<now)delete db.channels[id];});
    if(req.action==='createChannel'){
      RadioCore.nickname(p.nickname);if(!RadioCore.valid(p.ids,p.answers))throw Error('答案不完整');
      var id=Math.random().toString(36).slice(2,10).toUpperCase();
      db.channels[id]={id:id,hostName:p.nickname,hostAvatar:p.avatar,ids:p.ids,hostAnswers:p.answers,createdAt:new Date().toISOString(),expiresAt:now+365*86400000,attempts:[]};saveLocal(db);
      return {id:id,expiresAt:new Date(now+365*86400000).toISOString(),leaderboard:[]};
    }
    ch=db.channels[String(p.id||'').toUpperCase()];if(!ch)throw Error('找不到這個頻道，可能已經過期。');
    if(req.action==='getChannel')return publicChannel(ch);
    if(req.action==='submitGuess'){
      RadioCore.nickname(p.nickname);if(!RadioCore.valid(ch.ids,p.answers))throw Error('答案不完整');
      var old=ch.attempts.filter(function(x){return x.requestId===p.requestId;})[0];
      if(old)return resultFor(ch,old);
      var sc=RadioCore.score(ch.ids,ch.hostAnswers,p.answers),attempt={requestId:p.requestId,nickname:p.nickname,avatar:p.avatar,score:sc.score,answers:p.answers,createdAt:new Date().toISOString()};
      ch.attempts.push(attempt);saveLocal(db);return resultFor(ch,attempt);
    }
    throw Error('不支援的操作');
  }
  function boardFor(ch){return ch.attempts.slice().sort(function(a,b){return b.score-a.score||a.createdAt.localeCompare(b.createdAt);}).slice(0,20).map(function(x,i){return {rank:i+1,nickname:x.nickname,avatar:x.avatar,score:x.score,createdAt:x.createdAt};});}
  function publicChannel(ch){return {id:ch.id,hostName:ch.hostName,hostAvatar:ch.hostAvatar,ids:ch.ids,createdAt:ch.createdAt,expiresAt:new Date(ch.expiresAt).toISOString(),leaderboard:boardFor(ch)};}
  function resultFor(ch,attempt){var s=RadioCore.score(ch.ids,ch.hostAnswers,attempt.answers);return {score:s.score,points:s.points,hostAnswers:ch.hostAnswers,guestAnswers:attempt.answers,leaderboard:boardFor(ch)};}
  function siteBase(){var u=new URL(location.href);u.search='';u.hash='';return u.toString();}
  function jsonp(params){return new Promise(function(resolve,reject){var callback='__tongpin_'+Date.now()+'_'+Math.random().toString(36).slice(2),script=document.createElement('script'),done=false,timer;params.callback=callback;var u=new URL(remoteUrl);Object.keys(params).forEach(function(k){u.searchParams.set(k,params[k]);});function clean(){clearTimeout(timer);delete window[callback];script.remove();}window[callback]=function(value){if(done)return;done=true;clean();resolve(value);};script.onerror=function(){if(done)return;done=true;clean();reject(Error('無法連接 Google 紀錄服務。'));};timer=setTimeout(function(){if(done)return;done=true;clean();reject(Error('Google 紀錄服務回應逾時。'));},12000);script.src=u.toString();document.head.appendChild(script);});}
  function postForm(action,payload){var frame=document.createElement('iframe'),form=document.createElement('form'),input=document.createElement('input'),name='tongpin_post_'+Date.now()+'_'+Math.random().toString(36).slice(2);frame.name=name;frame.hidden=true;form.hidden=true;form.method='POST';form.action=remoteUrl;form.target=name;input.name='payload';input.value=JSON.stringify({action:action,payload:payload});form.appendChild(input);document.body.appendChild(frame);document.body.appendChild(form);form.submit();setTimeout(function(){form.remove();frame.remove();},30000);}
  function unwrapRemote(result){if(result&&result.ok){if(result.data)result.data.baseUrl=siteBase();return result.data;}throw Error(result&&result.error||'Google 紀錄服務發生錯誤。');}
  function waitRemote(requestId,attempt){return jsonp({api:'status',requestId:requestId}).then(function(result){if(result&&result.pending){if(attempt>=30)throw Error('儲存時間較久，請重新整理後再試一次。');return new Promise(function(resolve){setTimeout(resolve,700);}).then(function(){return waitRemote(requestId,attempt+1);});}return unwrapRemote(result);});}
  function remoteRpc(action,payload){if(action==='getChannel')return jsonp({api:'channel',id:payload.id}).then(unwrapRemote);postForm(action,payload);return new Promise(function(resolve){setTimeout(resolve,700);}).then(function(){return waitRemote(payload.requestId,0);});}
  function rpc(action,payload){
    if(!isGoogle&&remoteUrl)return remoteRpc(action,payload);
    if(!isGoogle)return Promise.resolve().then(function(){return localRpc({action:action,payload:payload});});
    return new Promise(function(resolve,reject){google.script.run.withSuccessHandler(function(r){if(r&&r.ok)resolve(r.data);else reject(Error(r&&r.error||'伺服器沒有回應'));}).withFailureHandler(function(e){reject(Error(e&&e.message||e||'連線失敗'));}).rpc({action:action,payload:payload});});
  }
  function avatarButtons(){return avatars.map(function(a){return '<button class="avatar" type="button" aria-label="頭像 '+a+'" aria-pressed="'+(state.avatar===a)+'" data-avatar="'+a+'">'+a+'</button>';}).join('');}
  function bindAvatars(){document.querySelectorAll('[data-avatar]').forEach(function(b){b.onclick=function(){state.avatar=b.dataset.avatar;document.querySelectorAll('[data-avatar]').forEach(function(x){x.setAttribute('aria-pressed',x===b);});};});}
  function home(){
    state.channel=null;document.title='默契電台 — 轉到彼此的頻率';
    app.innerHTML='<div class="home-grid fade-in"><section class="hero"><span class="eyebrow">NOW TUNING — 你的專屬頻道</span><h1>你們之間，<br>藏著什麼<em>頻率？</em></h1><p class="hero-description">先回答一組關於你的快問快答，再把頻道分享給朋友。<br>看誰最懂你，也看看意外的答案。</p><div class="hand-note">大約一首歌的時間就能完成</div><div class="radio" aria-hidden="true"><div class="radio-top"><span>TONGPIN 01</span><span>FRIENDSHIP RECEIVER</span></div><div class="radio-screen"><small>FM / SAME WAVELENGTH</small><div class="frequency">88.8<span>MHz</span></div><div class="tuner"></div></div><div class="radio-bottom"><div class="speaker"></div><div class="knob"></div></div><div class="sticker">FIND YOUR PEOPLE</div></div></section><section class="create-card"><div class="card-top"><span class="pill">● 建立新頻道</span><span>•••</span></div><h2>先讓電台認識你</h2><p class="subtle">這只是遊戲暱稱，請不要填真名或聯絡資料。</p><label class="field-label" for="nickname">你的暱稱</label><div class="nickname-wrap"><input id="nickname" type="text" maxlength="16" autocomplete="off" placeholder="例如：夜貓子" value="'+esc(state.nickname)+'"><span>✦</span></div><div id="name-error" class="error"></div><span class="field-label">選一個代表你的訊號</span><div class="avatars">'+avatarButtons()+'</div><span class="field-label">選擇題數</span><div class="mode-options"><button class="mode" type="button" aria-pressed="'+(state.count===8)+'" data-count="8"><strong>8 題 <span>推薦</span></strong><small>約 1 分鐘・輕快不拖戲</small></button><button class="mode" type="button" aria-pressed="'+(state.count===12)+'" data-count="12"><strong>12 題</strong><small>約 2 分鐘・多一點細節</small></button></div><button id="start" class="primary wide" type="button"><span>開始調頻</span><span>→</span></button><p class="microcopy">朋友只會看到暱稱、分數與排名；你的答案不會出現在分享網址。</p>'+(!isGoogle&&!remoteUrl?'<div class="preview-notice"><b>本機預覽模式</b>　現在可完整試玩；分享資料只存在這台裝置。填入 Google Apps Script 網址後會改用私人試算表。</div>':'')+'</section></div>';
    bindAvatars();document.querySelectorAll('[data-count]').forEach(function(b){b.onclick=function(){state.count=Number(b.dataset.count);document.querySelectorAll('[data-count]').forEach(function(x){x.setAttribute('aria-pressed',x===b);});};});
    document.getElementById('start').onclick=function(){try{state.nickname=RadioCore.nickname(document.getElementById('nickname').value);state.ids=RadioCore.select(state.count);state.answers=[];state.index=0;state.role='host';renderQuestion();}catch(e){document.getElementById('name-error').textContent=e.message;}};
  }
  function loadChallenge(id){
    app.innerHTML='<div class="section-card fade-in"><span class="loader"></span><h2>正在尋找頻率…</h2><p class="subtle">讀取頻道與目前排行榜</p></div>';
    rpc('getChannel',{id:id}).then(function(ch){state.channel=ch;renderJoin();}).catch(renderFatal);
  }
  function renderJoin(){var ch=state.channel,rows=rankingHtml(ch.leaderboard);
    document.title=ch.hostName+' 的默契挑戰｜默契電台';
    app.innerHTML='<div class="result-grid fade-in"><section class="section-card" style="margin:0"><span class="eyebrow">INCOMING SIGNAL</span><div class="big-emoji">'+esc(ch.hostAvatar)+'</div><h1>'+esc(ch.hostName)+' 正在等你</h1><p class="subtle">猜猜看 '+esc(ch.hostName)+' 會怎麼選。只有 '+ch.ids.length+' 題，很快就能知道你們有多同頻。</p><label class="field-label" for="nickname">排行榜暱稱</label><div class="nickname-wrap"><input id="nickname" type="text" maxlength="16" autocomplete="off" placeholder="請勿填真名或聯絡資料"><span>✦</span></div><div id="name-error" class="error"></div><span class="field-label">選擇訊號</span><div class="avatars">'+avatarButtons()+'</div><button id="join" class="primary wide" type="button"><span>接收挑戰</span><span>→</span></button><p class="microcopy">送出後，暱稱、分數與完成時間會顯示在這個頻道的排行榜。</p></section><section class="leaderboard"><span class="eyebrow">LIVE CHART</span><h2>目前排行榜</h2><ol class="ranking">'+rows+'</ol></section></div>';
    bindAvatars();document.getElementById('join').onclick=function(){try{state.nickname=RadioCore.nickname(document.getElementById('nickname').value);state.ids=ch.ids.slice();state.count=ch.ids.length;state.answers=[];state.index=0;state.role='guest';renderQuestion();}catch(e){document.getElementById('name-error').textContent=e.message;}};
  }
  function rankingHtml(items){if(!items||!items.length)return '<li class="empty">還沒有人上榜，你可以成為第一位。</li>';return items.map(function(x){return '<li><span class="rank-number">'+String(x.rank).padStart(2,'0')+'</span><span>'+esc(x.avatar)+'　'+esc(x.nickname)+'</span><strong>'+x.score+'%</strong></li>';}).join('');}
  function renderQuestion(){
    var q=RadioCore.get(state.ids[state.index]),answer=state.answers[state.index],pct=Math.round(state.index/state.ids.length*100),caption=q.type==='scale'?'拖曳滑桿，調到最接近你的刻度。':'別想太久，第一個直覺通常最準。';
    var body=q.type==='scale'?'<div class="scale-box"><div id="scale-value" class="scale-value">'+(answer==null?'拖曳開始調頻':esc(RadioCore.label(q,answer)))+'</div><input id="range" type="range" min="0" max="4" step="1" value="'+(answer==null?2:answer)+'" aria-label="'+esc(q.text)+'"><div class="scale-dots"><span>●</span><span>●</span><span>●</span><span>●</span><span>●</span></div><div class="scale-labels"><span>'+esc(q.options[0])+'</span><span>'+esc(q.options[1])+'</span></div></div>':'<div class="answers">'+q.options.map(function(o,i){return '<button class="answer" type="button" aria-pressed="'+(answer===i)+'" data-answer="'+i+'"><span class="answer-key">'+String.fromCharCode(65+i)+'</span><span>'+esc(o)+'</span></button>';}).join('')+'</div>';
    app.innerHTML='<section class="game fade-in"><div class="game-toolbar"><button id="exit" class="text-button" type="button">結束這局</button><span class="pill">'+(state.role==='host'?'建立我的頻道':'猜 '+esc(state.channel.hostName)+' 的答案')+'</span></div><div class="progress-track"><div style="width:'+pct+'%"></div></div><div class="question-meta"><span class="eyebrow">'+esc(RadioCore.groups[q.group])+'</span><span class="question-number"><strong>'+String(state.index+1).padStart(2,'0')+'</strong> / '+String(state.ids.length).padStart(2,'0')+'</span></div><h1>'+esc(q.text)+'</h1><p class="question-caption">'+caption+'</p>'+body+'<div class="game-actions"><span class="game-hint">'+(state.index?'可以返回修改上一題':'答案送出前都能修改')+'</span><div><button id="prev" class="secondary" type="button" '+(state.index?'':'disabled')+'>← 上一題</button> '+(q.type==='scale'?'<button id="next" class="primary" type="button" '+(answer==null?'disabled':'')+'><span>'+(state.index===state.ids.length-1?'完成':'下一題')+'</span><span>→</span></button>':'')+'</div></div></section>';
    document.getElementById('exit').onclick=function(){history.replaceState(null,'',location.pathname);home();};document.getElementById('prev').onclick=function(){state.index--;renderQuestion();};
    if(q.type==='pick')document.querySelectorAll('[data-answer]').forEach(function(b){b.onclick=function(){state.answers[state.index]=Number(b.dataset.answer);tone('tap');document.querySelectorAll('[data-answer]').forEach(function(x){x.setAttribute('aria-pressed',x===b);});setTimeout(next,260);};});
    else {var range=document.getElementById('range'),nextBtn=document.getElementById('next');range.oninput=function(){state.answers[state.index]=Number(range.value);document.getElementById('scale-value').textContent=RadioCore.label(q,state.answers[state.index]);nextBtn.disabled=false;tone('slide');};nextBtn.onclick=next;}
  }
  function next(){if(state.answers[state.index]==null)return;if(state.index===state.ids.length-1){finish();return;}state.index++;if(state.index%(state.count/4)===0)renderChapter();else renderQuestion();}
  function renderChapter(){var q=RadioCore.get(state.ids[state.index]),icons=['☕','🍜','🧭','💜'];app.innerHTML='<section class="section-card fade-in"><span class="eyebrow">SIGNAL LOCKED</span><div class="wave">'+[1,2,3,4,5,6,7,8,9].map(function(n){return '<i style="height:'+(10+(n*13)%36)+'px;animation-delay:'+n/12+'s"></i>';}).join('')+'</div><div class="big-emoji">'+icons[q.group]+'</div><h1>下一站：'+esc(RadioCore.groups[q.group])+'</h1><p class="subtle">目前已完成 '+state.index+' 題，訊號越來越清楚了。</p><button id="continue" class="primary wide" type="button"><span>繼續接收</span><span>→</span></button></section>';document.getElementById('continue').onclick=renderQuestion;}
  function finish(){state.role==='host'?createChannel():submitGuess();}
  function createChannel(){setBusy(true);app.innerHTML='<div class="section-card fade-in"><span class="loader"></span><h2>正在建立你的頻道…</h2><p class="subtle">答案會安全地存進站主的私人紀錄表</p></div>';rpc('createChannel',{nickname:state.nickname,avatar:state.avatar,ids:state.ids,answers:state.answers,version:RadioCore.version,requestId:requestId()}).then(function(data){state.channel={id:data.id,hostName:state.nickname,hostAvatar:state.avatar,ids:state.ids,leaderboard:[],baseUrl:data.baseUrl};renderShare(data.expiresAt);}).catch(renderFatal).finally(function(){setBusy(false);});}
  function shareUrl(){var u=new URL(state.channel&&state.channel.baseUrl||location.href);u.search='?q='+encodeURIComponent(state.channel.id);u.hash='';return u.toString();}
  function renderShare(expiresAt){var url=shareUrl(),date=expiresAt?new Date(expiresAt).toLocaleDateString('zh-TW'):'';if(!isGoogle)history.replaceState(null,'','?created='+encodeURIComponent(state.channel.id));app.innerHTML='<section class="section-card fade-in"><span class="eyebrow">YOU ARE ON AIR</span><div class="big-emoji">📻</div><h1>'+esc(state.nickname)+' 的頻道已開台</h1><p class="subtle">把這條連結傳給朋友。網址裡只有隨機頻道代碼，不含你的答案或個人資料。'+(date?'這個頻道預計在 '+esc(date)+' 失效。':'')+'</p><div class="share-box">'+esc(url)+'</div><div class="share-actions"><button id="share" class="primary" type="button"><span>分享給朋友</span><span>↗</span></button><button id="copy" class="secondary" type="button">複製連結</button><button id="open" class="secondary" type="button">預覽挑戰</button></div><div class="preview-notice">提醒：拿到連結的人可以參加並看見排行榜。請只分享給你想邀請的人。</div></section>';document.getElementById('copy').onclick=function(){copyText(url);};document.getElementById('share').onclick=function(){if(navigator.share)navigator.share({title:'來挑戰 '+state.nickname+' 的默契電台',text:'我開了一個默契頻道，猜猜我的答案！',url:url}).catch(function(){});else copyText(url);};document.getElementById('open').onclick=function(){isGoogle?window.open(url,'_blank','noopener'):location.href=url;};}
  function copyText(text){navigator.clipboard&&navigator.clipboard.writeText?navigator.clipboard.writeText(text).then(function(){toast('連結已複製');}).catch(function(){fallbackCopy(text);}):fallbackCopy(text);}
  function fallbackCopy(text){var t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();toast('連結已複製');}
  function submitGuess(){setBusy(true);app.innerHTML='<div class="section-card fade-in"><span class="loader"></span><h2>正在比對你們的頻率…</h2><p class="subtle">計算分數並更新排行榜</p></div>';rpc('submitGuess',{id:state.channel.id,nickname:state.nickname,avatar:state.avatar,answers:state.answers,version:RadioCore.version,requestId:requestId()}).then(renderResult).catch(renderFatal).finally(function(){setBusy(false);});}
  function scoreMessage(score){if(score>=90)return ['完全同頻！','連沉默都像在同一個節拍上。'];if(score>=70)return ['訊號超清楚','你真的有在認真接收對方。'];if(score>=50)return ['熟悉中帶點驚喜','有些答案，剛好留給下一次聊天。'];return ['不同台也很有趣','差異可能就是你們最好玩的地方。'];}
  function renderResult(data){var msg=scoreMessage(data.score),rows=rankingHtml(data.leaderboard),review=state.ids.map(function(id,i){var q=RadioCore.get(id);return '<div class="review-row"><span class="points">'+data.points[i]+' 分</span><b>'+esc(q.text)+'</b><p>'+esc(state.channel.hostName)+'：'+esc(RadioCore.label(q,data.hostAnswers[i]))+'<br>你：'+esc(RadioCore.label(q,data.guestAnswers[i]))+'</p></div>';}).join('');app.innerHTML='<div class="result-grid fade-in"><section class="score-card"><span class="eyebrow">MATCH RESULT</span><div class="score-orbit"><strong>'+data.score+'</strong><span>SIGNAL MATCH %</span></div><h2>'+msg[0]+'</h2><p>'+msg[1]+'</p><button id="share-score" class="secondary wide" type="button">分享我的成績 ↗</button></section><section class="leaderboard"><span class="eyebrow">LIVE CHART</span><h2>'+esc(state.channel.hostName)+' 的排行榜</h2><ol class="ranking">'+rows+'</ol><details class="review"><summary>查看每一題的答案對照</summary>'+review+'</details><button id="new-channel" class="primary wide" type="button" style="margin-top:22px"><span>換我建立頻道</span><span>→</span></button></section></div>';document.getElementById('new-channel').onclick=function(){if(!isGoogle)history.replaceState(null,'',location.pathname);state.nickname='';home();};document.getElementById('share-score').onclick=function(){var text='我和 '+state.channel.hostName+' 的默契是 '+data.score+'%！你也來挑戰：',url=shareUrl();if(navigator.share)navigator.share({title:'默契電台 '+data.score+'%',text:text,url:url}).catch(function(){});else copyText(text+' '+url);};}
  function renderFatal(e){setBusy(false);app.innerHTML='<section class="section-card fade-in"><span class="eyebrow">SIGNAL LOST</span><div class="big-emoji">📡</div><h1>暫時收不到訊號</h1><p class="subtle">'+esc(e&&e.message||'請稍後再試一次。')+'</p><button id="back-home" class="primary wide" type="button"><span>回到電台首頁</span><span>→</span></button></section>';document.getElementById('back-home').onclick=function(){history.replaceState(null,'',location.pathname);home();};}
  var audio={ctx:null,gain:null,timer:null,on:false,step:0};
  function startMusic(){var AC=window.AudioContext||window.webkitAudioContext;if(!AC){toast('這個瀏覽器不支援背景音樂');return;}if(!audio.ctx){audio.ctx=new AC();audio.gain=audio.ctx.createGain();audio.gain.gain.value=.055;audio.gain.connect(audio.ctx.destination);}audio.ctx.resume();audio.gain.gain.setTargetAtTime(.055,audio.ctx.currentTime,.05);audio.on=true;clearInterval(audio.timer);musicTick();audio.timer=setInterval(musicTick,850);syncMusic();}
  function musicTick(){if(!audio.on)return;var notes=[220,277.18,329.63,246.94,293.66,369.99,277.18,329.63],ctx=audio.ctx,t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=notes[audio.step++%notes.length];g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.23,t+.06);g.gain.exponentialRampToValueAtTime(.001,t+.8);o.connect(g);g.connect(audio.gain);o.start(t);o.stop(t+.85);}
  function stopMusic(){audio.on=false;clearInterval(audio.timer);if(audio.gain&&audio.ctx)audio.gain.gain.setTargetAtTime(.0001,audio.ctx.currentTime,.05);syncMusic();}
  function syncMusic(){var b=document.getElementById('music');b.setAttribute('aria-pressed',audio.on);document.getElementById('music-label').textContent=audio.on?'關閉音樂':'開啟音樂';}
  function tone(kind){if(!audio.on||!audio.ctx)return;var o=audio.ctx.createOscillator(),g=audio.ctx.createGain(),t=audio.ctx.currentTime;o.type='sine';o.frequency.value=kind==='tap'?660:440;g.gain.setValueAtTime(.05,t);g.gain.exponentialRampToValueAtTime(.001,t+.09);o.connect(g);g.connect(audio.ctx.destination);o.start(t);o.stop(t+.1);}
  document.getElementById('music').onclick=function(){audio.on?stopMusic():startMusic();};document.addEventListener('visibilitychange',function(){if(!audio.ctx||!audio.on)return;if(document.hidden){clearInterval(audio.timer);audio.ctx.suspend();}else{audio.ctx.resume();musicTick();audio.timer=setInterval(musicTick,850);}});
  var info=document.getElementById('info');document.getElementById('about').onclick=function(){info.showModal();};document.getElementById('privacy').onclick=function(){info.showModal();};document.getElementById('close-info').onclick=function(){info.close();};document.getElementById('clear-local').onclick=function(){localStorage.removeItem('tongpin-radio-db');localStorage.removeItem('tongpin-radio-progress');toast('這台裝置的遊戲進度已清除');info.close();};document.querySelector('.brand').onclick=function(e){e.preventDefault();home();};
  function startRoute(qid){qid?loadChallenge(String(qid).toUpperCase()):home();}
  if(isGoogle&&google.script.url&&google.script.url.getLocation)google.script.url.getLocation(function(loc){startRoute(loc&&loc.parameter&&loc.parameter.q);});else {var query=new URLSearchParams(location.search);startRoute(query.get('q'));}
})();
